stages:
  - coverage
  - upload

variables:
  COVERAGE_FILE: "coverage.info"
  COVERAGE_REPORT_DIR: "coverage"

coverage:
  stage: coverage
  tags:
    - code_coverage
  before_script:
    - |
      if ! command -v lcov &> /dev/null; then
        echo "lcov not found, installing..."
        apt-get update
        apt-get install -y lcov
      else
        echo "lcov is already installed"
      fi    
  script:
    - mkdir build
    - cd build
    - /mathworks/devel/sandbox/dozyurt/3PForR2024b/3p/install/unknown/glnxa64/cmake-bin/glnxa64/bin/cmake -DCMAKE_BUILD_TYPE=DEBUG -DALL_TESTS=ON -DBUILD_SHARED_LIBS=OFF -DHIGHS_COVERAGE=ON -DCI=OFF -DFAST_BUILD=OFF ..
    - make
    - /mathworks/devel/sandbox/dozyurt/3PForR2024b/3p/install/unknown/glnxa64/cmake-bin/glnxa64/bin/cmake --build . --target coverage
  artifacts:
    paths:
      - build/${COVERAGE_REPORT_DIR}
      - build/${COVERAGE_FILE}
      - build/Testing
    expire_in: 1 week

pages:
  stage: upload
  tags:
    - code_coverage
  script:
    - mv build/${COVERAGE_REPORT_DIR} public
  artifacts:
    paths:
      - public
  only:
    - CodeCoverage
  dependencies:
    - coverage
