stages:
  - coverage
  - upload

variables:
  COVERAGE_FILE: "coverage.info"
  COVERAGE_REPORT_DIR: "coverage"

coverage:
  stage: coverage
  tags:
    - code_coverage
  script:
    - mkdir build
    - cd build
    - make
    - /mathworks/devel/sandbox/dozyurt/3PForR2024b/3p/install/unknown/glnxa64/cmake-bin/glnxa64/bin/cmake -DCMAKE_BUILD_TYPE=DEBUG -DALL_TESTS=ON -DBUILD_SHARED_LIBS=OFF -DHIGHS_COVERAGE=ON -DLCOV_PATH=/home/dozyurt/Downloads/bin/lcov -DGENHTML_PATH=/home/dozyurt/Downloads/bin/genhtml -DCI=OFF -DFAST_BUILD=OFF ..
    - /mathworks/devel/sandbox/dozyurt/3PForR2024b/3p/install/unknown/glnxa64/cmake-bin/glnxa64/bin/cmake --build . --target coverage
  artifacts:
    paths:
      - build/${COVERAGE_REPORT_DIR}
      - build/${COVERAGE_FILE}
    expire_in: 1 week

pages:
  stage: upload
  tags:
    - code_coverage
  script:
    - mv build/${COVERAGE_REPORT_DIR} public
  artifacts:
    paths:
      - public
  only:
    - CodeCoverage
  dependencies:
    - coverage
