# [project.urls]
# "Source Code" = "https://github.com/ERGO-Code/HiGHS"
# "Bug Tracker" = "https://github.com/ERGO-Code/HiGHS/issues"

[build-system]
# Minimum requirements for the build system to execute.
requires = [
  "setuptools>=45",
  "pybind11>=2.4",
  "wheel>=0.2",
  "numpy>=1.7",
] 

build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp312-*"
skip = "cp3{6,7}-*"
test-skip = ""
