name: build-nuget-package

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # macos 12 is Intel
  build_macos_12:
    runs-on: macos-12
    # strategy:
      # matrix:
      #   python: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Build HiGHS
        run: |
         cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCSHARP=ON -DBUILD_DOTNET=ON

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config Release --parallel

      - uses: actions/upload-artifact@v4
        with:
          name: macos-x64
          path: ${{runner.workspace}}/build/dotnet/Highs.Native/runtimes
            
  # macos 14 is M1 (beta)
  build_macos_14:
    runs-on: macos-14 
    steps:
      - uses: actions/checkout@v4
      - name: Build HiGHS
        run: |
         cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCSHARP=ON -DBUILD_DOTNET=ON

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config Release --parallel

      - uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: ${{runner.workspace}}/build/dotnet/Highs.Native/runtimes

  # Build windows 32 and linux 
  build_windows_32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build HiGHS
        run: |
         cmake -E make_directory ${{runner.workspace}}/build32 

      - name: Configure CMake win32
        shell: bash
        working-directory: ${{runner.workspace}}/build32
        run: cmake $GITHUB_WORKSPACE -DCSHARP=ON -DBUILD_DOTNET=ON -A Win32

      - name: Build win32
        shell: bash
        working-directory: ${{runner.workspace}}/build32
        run: cmake --build . --config Release --parallel

      - uses: actions/upload-artifact@v4
        with:
          name: win-x32
          path: ${{runner.workspace}}/build/dotnet/Highs.Native/runtimes

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build HiGHS
        run: |
         cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCSHARP=ON -DBUILD_DOTNET=ON

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config Release --parallel

      - uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: ${{runner.workspace}}/build/dotnet/Highs.Native/runtimes

  build_linux_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build HiGHS
        run: |
         cmake -E make_directory ${{runner.workspace}}/build_linux_arm64

      - name: Configure CMake linux-arm-64
        working-directory: ${{runner.workspace}}/build_linux_arm64
        shell: bash
        run: cmake $GITHUB_WORKSPACE -DCSHARP=ON -DBUILD_DOTNET=ON -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/nuget/arm-toolchain.cmake

      - name: Build linux-arm-64
        working-directory: ${{runner.workspace}}/build_linux_arm64
        shell: bash
        run: cmake --build . --config Release --parallel

      - uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: ${{runner.workspace}}/build/dotnet/Highs.Native/runtimes

  build_windows:
    runs-on: windows-latest
    needs: [build_macos_12, build_macos_14, build_windows_32, build_linux, build_linux_arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Build HiGHS Windows native
        run: |
         cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake $GITHUB_WORKSPACE -DCSHARP=ON -DBUILD_DOTNET=ON

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config Release --parallel
      
      - name: Download runtimes
        uses: actions/download-artifact@v4
        with:
          name: macos-x64
          path: build/dotnet/Highs.Native/runtimes/macos-x64/

      - name: Download runtimes
        uses: actions/download-artifact@v4
        with:
          name: macos-arm64
          path: build/dotnet/Highs.Native/runtimes/macos-arm64/

      - name: Download runtimes
        uses: actions/download-artifact@v4
        with:
          name: win-x32
          path: build/dotnet/Highs.Native/runtimes/win-x32/

      - name: Download runtimes
        uses: actions/download-artifact@v4
        with:
          name: linux-x64
          path: build/dotnet/Highs.Native/runtimes/linux-x64/

      - name: Download runtimes
        uses: actions/download-artifact@v4
        with:
          name: linux-arm64
          path: build/dotnet/Highs.Native/runtimes/linux-arm64/

      - name: Display structure of downloaded files
        run: ls -R build/dotnet/Highs.Native/runtimes