name: code-coverage

on: [push, pull_request]

jobs:
  debug:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: install 
        run: sudo apt-get update && sudo apt-get install lcov 

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DHIGHS_COVERAGE=ON -DALL_TESTS=ON -DBUILD_SHARED_LIBS=OFF

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          cmake --build . --parallel --config Debug

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest --parallel --timeout 300 --output-on-failure 

      - name: Generate report with lcov
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          lcov -d . -c -o cov.info --ignore-errors empty
          lcov --remove cov.info "/usr/include/*" -o cov.info
          lcov --remove cov.info "/usr/lib/*" -o cov.info
          lcov --remove cov.info "extern/pdqsort/*" -o cov.info
          lcov --remove cov.info "extern/zstr/*" -o cov.info
          lcov --remove cov.info "extern/catch*" -o cov.info
          lcov --remove cov.info "app/cxxopts*" -o cov.info
          lcov --remove cov.info "src/test*" -o cov.info
          lcov --list cov.info

          

