name: release-archive-artifact.yml

on:
  push:
    # tags:
    #   - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/archive

      - name: Generate archive artifact
        run: |
          pwd
          ls 
          echo $GITHUB_WORKSPACE

      - name: working dir
        run: |
          cd archive 
          tar -czvf source-archive.tar.gz $GITHUB_WORKSPACE --exclude='./archive'

      - name: Release
        uses: softprops/action-gh-release@v2

        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            archive/source-archive.tar.gz