name: release-archive-artifact.yml

on:
  push:
    # tags:
    #   - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate archive artifact
        run: |
          pwd
          ls 
          echo $GITHUB_WORKSPACE
          echo ${runner.workspace}
          cd ..
          ls

      - name: working dir
        run: |
          pwd
          ls 
        # tar -czvf source-archive.tar.gz $GITHUB_WORKSPACE

      - name: Release
        uses: softprops/action-gh-release@v2

        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            source-archive.tar.gz