name: release-archive-artifact.yml

on: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate archive artefact
        run: tar ...

      - name: Release
        uses: softprops/action-gh-release@v2

        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            LICENSE