name: sanitizers-bazel

on: [push, pull_request]

jobs:
  bazel:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: bazelbuild/setup-bazelisk@v3

      - name: Bazel clean
        run: bazel clean
      
      - name: Bazel build
        run: bazel build -c dbg --config=tsan //...
      
      - name: Bazel test
        run: bazel test -c dbg --config=tsan //...

      - name: Upload bazel-testlogs
        uses: actions/upload-artifact@v4
        with:
          name: bazel-testlogs
          path: bazel-testlogs/