name: test-fortran-macos

on: [push, pull_request]

jobs:
  fast_build_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install GFortran
        run: brew install gfortran gcc

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build
        
      - name: Symlink gfortran (macOS)
        run: |
          # make sure gfortran is available
          # https://github.com/actions/virtual-environments/issues/2524
          # https://github.com/cbg-ethz/dce/blob/master/.github/workflows/pkgdown.yaml
          gfortran-11 --version
          gcc-11 --version 
          whereis gcc-11
          gcc --version
          ls  /usr/local/Cellar/gcc@11/*/lib/gcc/11
          sudo ln -s /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
          sudo mkdir /usr/local/gfortran
          sudo ln -s /usr/local/Cellar/gcc@11/*/lib/gcc/11 /usr/local/gfortran/lib
          gfortran --version
          
      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --version
          gfortran-11 --version
          cmake $GITHUB_WORKSPACE -DFORTRAN=ON 

      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --parallel

      - name: Test
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          ls 
          ./bin/fortrantest
