name: Test python package
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        # shell: bash -l {0}
        run: |
          python3 -m pip install setuptools
          python3 setup.py sdist


      - name: Install sdist
        run: |
          ls dist
          python3 -m pip install dist/*.tar.gz

      - name: Test highspy
        run: |
          python3 -m pip install pytest
          python3 -m pytest $GITHUB_WORKSPACE/highspy/tests/test_highspy.py
          
  # build_wheels:
  #   name: Build wheel for ${{ matrix.python }}-${{ matrix.buildplat[1] }}
  #   runs-on: ${{ matrix.buildplat[0] }}
  #   environment: pypi
  #   strategy:
  #     # Ensure that a wheel builder finishes even if another fails
  #     fail-fast: false
  #     matrix:
  #       # From NumPy
  #       # Github Actions doesn't support pairing matrix values together, let's improvise
  #       # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
  #       buildplat:
  #         - [ubuntu-20.04, manylinux_x86_64]
  #         - [ubuntu-20.04, musllinux_x86_64] # No OpenBlas, no test
  #         - [macos-12, macosx_x86_64]
  #         - [macos-12, macosx_arm64]
  #         - [windows-2019, win_amd64]
  #       python: ["cp38", "cp39","cp310", "cp311","cp312"]

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build wheels
  #       uses: pypa/cibuildwheel@v2.12.3
  #       env:
  #         CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         path: ./wheelhouse/*.whl
