name: test-python-package
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: |
          python3 -m pip install setuptools
          python3 setup.py sdist

      - name: Install sdist
        run: |
          ls dist
          python3 -m pip install dist/*.tar.gz

      - name: Test highspy
        run: |
          python3 -m pip install pytest
          python3 -m pytest $GITHUB_WORKSPACE/highspy/tests/test_highspy.py
          
  build_sdist_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: |
          python3 -m pip install setuptools
          python3 setup.py sdist

      - name: Install sdist
        run: |
          ls dist
          python3 -m pip install dist/*.tar.gz

      - name: Test highspy
        run: |
          python3 -m pip install pytest
          python3 -m pytest $GITHUB_WORKSPACE/highspy/tests/test_highspy.py

  build_sdist_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: |
          python -m pip install setuptools
          python setup.py sdist

      - name: Install sdist
        run: |
          ls dist
          python -m pip install dist/*.tar.gz

      - name: Test highspy
        run: |
          python -m pip install pytest
          python -m pytest $GITHUB_WORKSPACE/highspy/tests/test_highspy.py
             
  build_wheel_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build wheel
        run: |
          python3 -m pip install cibuildwheel
          python3 -m cibuildwheel --only cp310-manylinux_x86_64 $GITHUB_WORKSPACE

      - name: Install wheel
        run: |
          ls wheelhouse
          python3 -m pip install wheelhouse/*.whl

      - name: Test highspy
        run: |
          python3 -m pip install pytest
          python3 -m pytest $GITHUB_WORKSPACE/highspy/tests/test_highspy.py
          
  build_wheel_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build wheel
        run: |
          python3 -m pip install cibuildwheel
          python3 -m cibuildwheel --only cp310-macosx_x86_64 $GITHUB_WORKSPACE

      - name: Install wheel
        run: |
          ls wheelhouse
          python3 --version
          python3 -m pip install wheelhouse/*.whl

      - name: Test highspy
        run: |
          python3 -m pip install pytest
          python3 -m pytest $GITHUB_WORKSPACE/highspy/tests/test_highspy.py
          
  build_wheel_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build wheel
        run: |
          python -m pip install cibuildwheel
          python -m cibuildwheel --only cp310-win_amd64 $GITHUB_WORKSPACE

      - name: Install wheel
        run: |
          ls wheelhouse
          python -m pip install wheelhouse/*.whl

      - name: Test highspy
        run: |
          python -m pip install pytest
          python -m pytest $GITHUB_WORKSPACE/highspy/tests/test_highspy.py
          