# python release WIP
name: test-python-mac

on: []
#on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [self-hosted, macos]
        python: [3.12]
    steps:
      - uses: actions/checkout@v3
      - name: Install correct python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build
  
      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build /
            -DPYTHON=ON -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/build/highspy/

      - name: Test Python Interface
        shell: bash
        run: |
          cmake --build ${{runner.workspace}}/build --parallel 
          cmake --install ${{runner.workspace}}/build
          cd ${{runner.workspace}}/build/highspy
          pip install -vvv .
          pip install pytest numpy
          pytest -v ./highspy/tests/
  